
language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

install:
    - npm install -g vuepress@next
    - npm install

script:
    - npm run docs:build
    - echo learn.libre.solar >> docs/.vuepress/dist/CNAME

cache:
    directories:
        - "node_modules"

notifications:
    email: false

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    local_dir: docs/.vuepress/dist
    keep-history: false
    on:
        branch: master