
language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

install:
    - npm install -g vuepress@next
    - npm install

script:
    - ./deploy.sh

cache:
    directories:
        - "node_modules"

notifications:
    email: false

deploy:
    provider: pages
    fqdn: learn.libre.solar
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    local_dir: gh-pages
    keep-history: false
    on:
        all_branches: true